// countries-data.js
// 국가 리스트: code = 계산기에 넘길 코드, slug = URL 경로, name = 화면에 보일 이름
// 필요하면 계속 추가 가능
const countries = [
  { code: 'us', slug: 'united-states', name: 'United States' },
  { code: 'ca', slug: 'canada', name: 'Canada' },
  { code: 'uk', slug: 'united-kingdom', name: 'United Kingdom' },
  { code: 'de', slug: 'germany', name: 'Germany' },
  { code: 'fr', slug: 'france', name: 'France' },
  { code: 'es', slug: 'spain', name: 'Spain' },
  { code: 'it', slug: 'italy', name: 'Italy' },
  { code: 'pt', slug: 'portugal', name: 'Portugal' },
  { code: 'nl', slug: 'netherlands', name: 'Netherlands' },
  { code: 'be', slug: 'belgium', name: 'Belgium' },
  { code: 'ch', slug: 'switzerland', name: 'Switzerland' },
  { code: 'at', slug: 'austria', name: 'Austria' },
  { code: 'se', slug: 'sweden', name: 'Sweden' },
  { code: 'no', slug: 'norway', name: 'Norway' },
  { code: 'dk', slug: 'denmark', name: 'Denmark' },
  { code: 'fi', slug: 'finland', name: 'Finland' },
  { code: 'ie', slug: 'ireland', name: 'Ireland' },
  { code: 'pl', slug: 'poland', name: 'Poland' },
  { code: 'cz', slug: 'czech-republic', name: 'Czech Republic' },
  { code: 'sk', slug: 'slovakia', name: 'Slovakia' },
  { code: 'hu', slug: 'hungary', name: 'Hungary' },
  { code: 'ro', slug: 'romania', name: 'Romania' },
  { code: 'bg', slug: 'bulgaria', name: 'Bulgaria' },
  { code: 'gr', slug: 'greece', name: 'Greece' },
  { code: 'tr', slug: 'turkey', name: 'Turkey' },
  { code: 'ru', slug: 'russia', name: 'Russia' },
  { code: 'ua', slug: 'ukraine', name: 'Ukraine' },
  { code: 'ee', slug: 'estonia', name: 'Estonia' },
  { code: 'lv', slug: 'latvia', name: 'Latvia' },
  { code: 'lt', slug: 'lithuania', name: 'Lithuania' },
  { code: 'hr', slug: 'croatia', name: 'Croatia' },
  { code: 'si', slug: 'slovenia', name: 'Slovenia' },
  { code: 'lu', slug: 'luxembourg', name: 'Luxembourg' },
  { code: 'is', slug: 'iceland', name: 'Iceland' },

  // 북미/중남미
  { code: 'mx', slug: 'mexico', name: 'Mexico' },
  { code: 'br', slug: 'brazil', name: 'Brazil' },
  { code: 'ar', slug: 'argentina', name: 'Argentina' },
  { code: 'cl', slug: 'chile', name: 'Chile' },
  { code: 'co', slug: 'colombia', name: 'Colombia' },
  { code: 'pe', slug: 'peru', name: 'Peru' },
  { code: 'uy', slug: 'uruguay', name: 'Uruguay' },
  { code: 'cr', slug: 'costa-rica', name: 'Costa Rica' },
  { code: 'pa', slug: 'panama', name: 'Panama' },

  // 아시아/오세아니아
  { code: 'au', slug: 'australia', name: 'Australia' },
  { code: 'nz', slug: 'new-zealand', name: 'New Zealand' },
  { code: 'jp', slug: 'japan', name: 'Japan' },
  { code: 'kr', slug: 'south-korea', name: 'South Korea' },
  { code: 'cn', slug: 'china', name: 'China' },
  { code: 'hk', slug: 'hong-kong', name: 'Hong Kong' },
  { code: 'tw', slug: 'taiwan', name: 'Taiwan' },
  { code: 'sg', slug: 'singapore', name: 'Singapore' },
  { code: 'my', slug: 'malaysia', name: 'Malaysia' },
  { code: 'th', slug: 'thailand', name: 'Thailand' },
  { code: 'vn', slug: 'vietnam', name: 'Vietnam' },
  { code: 'id', slug: 'indonesia', name: 'Indonesia' },
  { code: 'ph', slug: 'philippines', name: 'Philippines' },
  { code: 'in', slug: 'india', name: 'India' },
  { code: 'pk', slug: 'pakistan', name: 'Pakistan' },
  { code: 'bd', slug: 'bangladesh', name: 'Bangladesh' },
  { code: 'lk', slug: 'sri-lanka', name: 'Sri Lanka' },
  { code: 'ae', slug: 'united-arab-emirates', name: 'United Arab Emirates' },
  { code: 'sa', slug: 'saudi-arabia', name: 'Saudi Arabia' },
  { code: 'qa', slug: 'qatar', name: 'Qatar' },
  { code: 'kw', slug: 'kuwait', name: 'Kuwait' },
  { code: 'bh', slug: 'bahrain', name: 'Bahrain' },
  { code: 'om', slug: 'oman', name: 'Oman' },
  { code: 'jo', slug: 'jordan', name: 'Jordan' },
  { code: 'il', slug: 'israel', name: 'Israel' },

  // 아프리카
  { code: 'za', slug: 'south-africa', name: 'South Africa' },
  { code: 'ng', slug: 'nigeria', name: 'Nigeria' },
  { code: 'ke', slug: 'kenya', name: 'Kenya' },
  { code: 'eg', slug: 'egypt', name: 'Egypt' },
  { code: 'ma', slug: 'morocco', name: 'Morocco' },
  { code: 'gh', slug: 'ghana', name: 'Ghana' },
  { code: 'tn', slug: 'tunisia', name: 'Tunisia' },
  { code: 'et', slug: 'ethiopia', name: 'Ethiopia' },
  { code: 'dz', slug: 'algeria', name: 'Algeria' },

  // 기타 디지털 노마드/원격 인기 국가
  { code: 'mt', slug: 'malta', name: 'Malta' },
  { code: 'cy', slug: 'cyprus', name: 'Cyprus' },
  { code: 'ge', slug: 'georgia', name: 'Georgia' },
  { code: 'rs', slug: 'serbia', name: 'Serbia' },
  { code: 'ba', slug: 'bosnia-herzegovina', name: 'Bosnia and Herzegovina' },
  { code: 'md', slug: 'moldova', name: 'Moldova' },
  { code: 'mk', slug: 'north-macedonia', name: 'North Macedonia' },
  { code: 'al', slug: 'albania', name: 'Albania' },
];

module.exports = { countries };
